# Generated by Django 2.2 on 2023-01-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230106_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={},
        ),
    ]
